# -*- coding: utf-8 -*-
"""SEABORN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sn4edAg0QNy8s8tqJqVmVM2ny1wWttiD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



print(sns.get_dataset_names())

"""## **Line plot**"""

x = np.linspace(0,10,100)
plt.plot(x,np.sin(x),x,np.cos(x))
plt.show()

sns.set()
x = np.linspace(0,10,100)
plt.plot(x,np.sin(x),x,np.cos(x))
plt.show()

fmri = sns.load_dataset("fmri")
sns.lineplot(x= "timepoint", y = "signal",data = fmri)

sns.lineplot(x = "timepoint",y = "signal",hue = "event",style = "region",data = fmri,markers = True,dashes=False)
plt.xlabel("Timepoint")
plt.ylabel("Signal Intensity")
plt.title("Changes in Signal Intensity over Time")
plt.show()

"""## **Scatterplot**"""

df = sns.load_dataset('tips')
sns.scatterplot(x='total_bill', y='tip', data=df)

sns.set()
tips = sns.load_dataset("tips")
sns.scatterplot(x="total_bill", y="tip", hue="sex", size="size", sizes=(50, 200), data=tips)
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.title("Relationship between Total Bill and Tip")
plt.show()

"""## **Bar Plot**"""

titanic = sns.load_dataset("titanic")
sns.barplot(x = "class",y = "fare",data = titanic)

sns.barplot(x = "class",y= "fare",hue = "sex",data=titanic)
plt.xlabel("Class")
plt.ylabel("Fare")
plt.title("Average Fare by Class and Gender on the Titanic")

"""## **Histrogram plot**"""

iris = sns.load_dataset("iris")
iris

sns.histplot(x = 'petal_length',data = iris)

sns.histplot(data=iris, x="petal_length", bins=20,kde = True, color="green")
plt.xlabel("Petal Length (cm)")
plt.ylabel("Frequency")
plt.title("Distribution of Petal Lengths in Iris Flowers")
plt.show()

"""## **Density plot**"""

tips

tips = sns.load_dataset("tips")

sns.kdeplot(data=tips, x="total_bill")

sns.kdeplot(data = tips , x = 'total_bill',hue = 'time',fill = True ,alpha = 0.5,linewidth = 0.9)
plt.title("Density Plot of Total Bill by Meal Time")
plt.xlabel("Total Bill ($)")
plt.ylabel("Density")
plt.show()

"""## **Box plot**"""

sns.boxplot(x = "day",y = 'total_bill',data=tips)

sns.boxplot(x = "day",y = 'total_bill',hue = 'time',palette='Set3',data=tips,fliersize = 4,linewidth = 1.5)
plt.title("Box Plot of Total Bill by Day and Meal Time")
plt.xlabel("Day of the Week")
plt.ylabel("Total Bill ($)")

"""## **Violin plot**"""

iris = sns.load_dataset('iris')
iris

sns.violinplot(x = 'species', y = "petal_length",data = iris)

"""## **Seaborn Pair Chart**"""

iris = sns.load_dataset("iris")
iris

sns.pairplot(data=iris)
plt.show()

sns.pairplot(data= iris ,hue = "species",diag_kind="kde",palette="husl")
plt.title("Iris Dataset Pair Plot")
plt.show()

"""## **Joint Plot**"""

sns.jointplot(x = "sepal_length",y = "sepal_width",data = iris)

"""## **Facet Grids**"""

sns.set()
tips = sns.load_dataset("tips")
g = sns.FacetGrid(data =tips,col = 'day')
g.map(sns.histplot,'total_bill')

"""## **Relplot**"""

df = sns.load_dataset("tips")

sns.relplot(x = "total_bill",y = "tip",data = tips,hue = "sex")

sns.relplot(x = "total_bill",y = "tip",data = tips,hue = "sex",size = "time")

sns.relplot(x = "total_bill",y = "tip",data = tips,col ='size')

sns.relplot(x = "total_bill",y = "tip",data = tips,col = 'time')

sns.relplot(x = "total_bill",y = "tip",data = tips,col = 'smoker')

sns.relplot(x = 'total_bill' , y ='tip' , data = df , hue = 'sex' , style = 'time')

sns.relplot(x = 'total_bill', y = 'tip', data = tips, kind = 'scatter')
plt.show()

ds = sns.load_dataset("flights")
ds

sns.relplot(x = "year",y = "passengers",data = ds,kind = "line")

sns.relplot(x = "year",y = "passengers",data = ds,kind = "line",hue = 'month')

sns.relplot(x = 'year', y = 'passengers', data = ds, kind = 'line',col = 'month')
plt.show()

"""## **Catplot**"""

sns.catplot(x = "sex",y = 'total_bill',data = tips,kind = "box")

sns.catplot(x = "sex",y = 'total_bill',data = tips,kind = "violin")

sns.catplot(x = 'species', y = 'sepal_width', data = iris, kind = 'violin')
plt.show()